In [2]:
import os
import sys

import pandas as pd
import numpy as np
import scipy
from scipy import linalg
import math
from sympy import solve
from sympy import Symbol

# latex and markdown drafts

$$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$$

| This | is   |
|------|------|
|   a  | table|

# Questão 3

In [3]:
m_B = np.matrix([[7,3,0,2,-3],[3,6,-1,2,2],[0,-1,14,-1,6],[2,2,-1,3,-1],[-3,2,6,-1,7]])
m_B

matrix([[ 7,  3,  0,  2, -3],
        [ 3,  6, -1,  2,  2],
        [ 0, -1, 14, -1,  6],
        [ 2,  2, -1,  3, -1],
        [-3,  2,  6, -1,  7]])

In [4]:
np.transpose(m_B) == m_B

matrix([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]], dtype=bool)

In [5]:
eigstuff = np.linalg.eig(m_B)

m_eigvalues = eigstuff[0]
m_eigvalues = np.diag(m_eigvalues)

m_eigvectors = eigstuff[1]

In [6]:
eigstuff[0]

array([  1.78782743e+01,   1.03489151e+01,   6.81658356e+00,
         6.50669554e-03,   1.94972029e+00])

In [18]:
m_eigvalues

array([[  1.78782743e+01,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   1.03489151e+01,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   6.81658356e+00,
          0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          6.50669554e-03,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   1.94972029e+00]])

In [8]:
m_eigvalues_root = m_eigvalues**(1/2)
m_eigvalues_root

array([[ 4.22827084,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  3.21697298,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  2.61085878,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.08066409,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.39632385]])

In [20]:
m_eigvectors

matrix([[-0.17620215, -0.7054622 ,  0.39794698,  0.45089513,  0.3310705 ],
        [-0.04903154, -0.5924338 , -0.57876833, -0.53979537,  0.1423597 ],
        [ 0.83207956, -0.2192238 ,  0.40201825, -0.29419806, -0.10683336],
        [-0.12045337, -0.32083078, -0.04666762,  0.16972375, -0.92280798],
        [ 0.50959131, -0.01880998, -0.58555007,  0.62446449,  0.08448726]])

In [21]:
m_eigvectors_inv = np.linalg.inv(m_eigvectors)
m_eigvectors_inv

matrix([[-0.17620215, -0.04903154,  0.83207956, -0.12045337,  0.50959131],
        [-0.7054622 , -0.5924338 , -0.2192238 , -0.32083078, -0.01880998],
        [ 0.39794698, -0.57876833,  0.40201825, -0.04666762, -0.58555007],
        [ 0.45089513, -0.53979537, -0.29419806,  0.16972375,  0.62446449],
        [ 0.3310705 ,  0.1423597 , -0.10683336, -0.92280798,  0.08448726]])

In [22]:
m_B_diag = m_eigvectors_inv.dot(m_eigvalues_root).dot(m_eigvectors)
m_B_diag

matrix([[ 2.31042697,  0.13251914,  0.25197241, -0.4472238 , -0.4321182 ],
        [ 0.13251914,  3.36767134, -0.2975013 , -0.16860884, -1.17605044],
        [ 0.25197241, -0.2975013 ,  2.64809015,  0.94371782,  0.11427329],
        [-0.4472238 , -0.16860884,  0.94371782,  2.56979778,  0.5270745 ],
        [-0.4321182 , -1.17605044,  0.11427329,  0.5270745 ,  0.63710431]])

# Questão 4

In [24]:
m_A4 = np.matrix([[2/3,-1/3,2/3],[2/3,2/3,-1/3],[-1/3,2/3,2/3]])
m_A4

matrix([[ 0.66666667, -0.33333333,  0.66666667],
        [ 0.66666667,  0.66666667, -0.33333333],
        [-0.33333333,  0.66666667,  0.66666667]])

In [25]:
eigstuff = np.linalg.eig(m_A4)

m_eigvalues = eigstuff[0]
m_eigvalues = np.diag(m_eigvalues)

m_eigvectors = eigstuff[1]

In [26]:
m_eigvalues

array([[ 0.5+0.8660254j,  0.0+0.j       ,  0.0+0.j       ],
       [ 0.0+0.j       ,  0.5-0.8660254j,  0.0+0.j       ],
       [ 0.0+0.j       ,  0.0+0.j       ,  1.0+0.j       ]])

Olhando os autovetores, vemos que o autovetor correspondente ao autovalor $\lambda$ = 1, na última coluna, é um múltiplo de (1,1,1).

In [27]:
m_eigvectors

matrix([[-0.28867513+0.5j, -0.28867513-0.5j,  0.57735027+0.j ],
        [ 0.57735027+0.j ,  0.57735027-0.j ,  0.57735027+0.j ],
        [-0.28867513-0.5j, -0.28867513+0.5j,  0.57735027+0.j ]])

Agora, precisamos encontrar vetores ortogonais a este (podemos descartar os outros autovetores).

In [32]:
m_eigvectors_ort = np.matrix([[0,-2,1],[1,1,1],[-1,1,1]])
m_eigvectors_ort

matrix([[ 0, -2,  1],
        [ 1,  1,  1],
        [-1,  1,  1]])

In [33]:
m_eigvectors_inv = np.linalg.inv(m_eigvectors_ort)
m_eigvectors_inv

matrix([[  5.55111512e-17,   5.00000000e-01,  -5.00000000e-01],
        [ -3.33333333e-01,   1.66666667e-01,   1.66666667e-01],
        [  3.33333333e-01,   3.33333333e-01,   3.33333333e-01]])

In [35]:
m_eigvalues_ort = np.matrix([[1,0,0],[0,1,0],[0,0,1]])
m_eigvalues_ort

matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [39]:
m_B_diag = m_eigvectors_inv.dot(m_eigvalues).dot(m_eigvectors_ort)
m_B_diag

matrix([[ 0.75000000-0.4330127j , -0.25000000-0.4330127j ,
         -0.25000000-0.4330127j ],
        [-0.08333333-0.14433757j,  0.58333333+0.4330127j ,
          0.08333333-0.4330127j ],
        [-0.16666667-0.28867513j,  0.16666667-0.8660254j ,  0.66666667+0.j        ]])

# Questão 5

teste

In [11]:
m_A = np.matrix([[1,2],[1,1]])
P,L,U = scipy.linalg.lu(m_A, permute_l=False)
print(P)
print(L)
print(U)

[[ 1.  0.]
 [ 0.  1.]]
[[ 1.  0.]
 [ 1.  1.]]
[[ 1.  2.]
 [ 0. -1.]]


Matriz

In [12]:
m_A = np.matrix([[0.4619, 1.6439, 0.7844, 0.9046],[0.5105, 1.8065, -0.1813, -0.3618], [-0.8269, 0.7596, -0.2948, 0.0655], 
                 [-0.5323, 0.6103, -0.9824, -0.9790]])
m_A

matrix([[ 0.4619,  1.6439,  0.7844,  0.9046],
        [ 0.5105,  1.8065, -0.1813, -0.3618],
        [-0.8269,  0.7596, -0.2948,  0.0655],
        [-0.5323,  0.6103, -0.9824, -0.979 ]])

In [19]:
P,L,U = scipy.linalg.lu(m_A )
print(P)
print(L)
print(U)

[[ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]]
[[ 1.          0.          0.          0.        ]
 [-0.61736607  1.          0.          0.        ]
 [-0.55859233  0.90892157  1.          0.        ]
 [ 0.64372959  0.05331822 -0.81400917  1.        ]]
[[ -8.26900000e-01   7.59600000e-01  -2.94800000e-01   6.55000000e-02]
 [  0.00000000e+00   2.27545126e+00  -3.63299516e-01  -3.21362523e-01]
 [  0.00000000e+00   0.00000000e+00   9.49937747e-01   1.23328113e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00  -1.27669599e-04]]


In [34]:
U[3][3]=0
U

array([[-0.8269    ,  0.7596    , -0.2948    ,  0.0655    ],
       [ 0.        ,  2.27545126, -0.36329952, -0.32136252],
       [ 0.        ,  0.        ,  0.94993775,  1.23328113],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [35]:
np.linalg.qr(U)

(array([[ 1.,  0.,  0.,  0.],
        [-0.,  1.,  0.,  0.],
        [-0., -0.,  1.,  0.],
        [-0., -0., -0.,  1.]]),
 array([[-0.8269    ,  0.7596    , -0.2948    ,  0.0655    ],
        [ 0.        ,  2.27545126, -0.36329952, -0.32136252],
        [ 0.        ,  0.        ,  0.94993775,  1.23328113],
        [ 0.        ,  0.        ,  0.        ,  0.        ]]))

#  strang pg 368

In [3]:
m_C = np.matrix([[2,-1], [-1,2]])
m_C

matrix([[ 2, -1],
        [-1,  2]])

In [4]:
m_C_Ct = m_C.dot(np.transpose(m_C))
m_C_Ct

matrix([[ 5, -4],
        [-4,  5]])

In [6]:
np.transpose(m_C)

matrix([[ 2, -1],
        [-1,  2]])

In [5]:
m_Ct_C = np.transpose(m_C).dot(m_C)
m_Ct_C

matrix([[ 5, -4],
        [-4,  5]])